### ISSUE TITLE
Start up error in Sierra 10.12.2

### ISSUE THREAD

**Issue by casperschipper** [GameOfLife/WFSCollider#38]
When I run WFSCollider on my Sierra 10.12.2 (iMac), it gives this error:

```
ERROR: Primitive '_FilePutString' failed.
Failed.
RECEIVER:
Instance of File {    (0x10b495168, gc=B4, fmt=00, flg=00, set=02)
  instance variables [1]
    fileptr : nil
}
CALL STACK:
	MethodError:reportError   0x10b3c8f78
		arg this = <instance of PrimitiveFailedError>
	Nil:handleError   0x10b3c9028
		arg this = nil
		arg error = <instance of PrimitiveFailedError>
	Thread:handleError   0x10b3c90d8
		arg this = <instance of Thread>
		arg error = <instance of PrimitiveFailedError>
	Object:throw   0x10b3c9238
		arg this = <instance of PrimitiveFailedError>
	Object:primitiveFailed   0x10b3c9658
		arg this = <instance of File>
	OSXPlatform:writeClientCSS   0x10b7124a8
		arg this = <instance of OSXPlatform>
		var theme = <instance of Event>
		var file = <instance of File>
		var string = ".str { color: #606060; } /* ..."
	Meta_Document:setTheme   0x10b3d1e78
		arg this = <instance of Meta_CocoaDocument>
		arg themeName = 'default'
	Meta_CocoaDocument:startup   0x10b3d3948
		arg this = <instance of Meta_CocoaDocument>
		var post = nil
	OSXPlatform:startup   0x10b3d40d8
		arg this = <instance of OSXPlatform>
	Main:startup   0x10b9a4708
		arg this = <instance of Main>
For advice: [http://supercollider.sf.net/wiki/index.php/PrimitiveFailedError]
```

**Comment by woutersnoei** [comment]
Hmm, strange, what happens if you manually remove the following file inside the app bundle:
(...)/WFSCollider.app/Contents/Resources/Help/frontend.css
And then start again? (can't reproduce here on same system version)

**Comment by casperschipper** [comment]
Thanks, I'm afraid removing the .css still results in the same error.
Mysteriously enough, I did find that your version v2.2.3b6 (wijgaannaarmars) does run without any problem.

Maybe I should compare the file trees to see what is different ?

**Comment by woutersnoei** [comment]
It sounds like a permissions issue. Was the install copied from another machine perhaps? Or was it already there and working before the system update? In the first case; perhaps re-downloading the app from sourceforge could help.

**Comment by casperschipper** [comment]
Yes, this works ! I think I have found the problem. When I installed WFSCollider, I created a folder within applications, called it WFSCollider and then copied the application, documentation and examples into that folder. This used to work (at least in previous OS) but not in OS X Sierra. 

The solution is not making a folder but only installing the application and then storing the documentation and examples somewhere else.

**Comment by woutersnoei** [comment]
Hmm, still can't reproduce that, when I put a fresh copy of WFSCollider in a folder with that name it still works. Glad the issue is solved in this case but still wondering how and why ;-). Perhaps there was a strange character in the name of the folder somewhere? The issue indicated that WFSCollider was unable to write that certain .css file. We don't know if it was only that file it couldn't write or if it was having trouble writing anything inside the app bundle contents. In any case it was a generic supercollider issue, not specifically WFSCollider related. Of course we use an older version of SC as a base for the app, which could at some point become problematic on newer macOS versions..
